### ISSUE TITLE
cannot run the demo

### ISSUE THREAD

**Issue by zydp** [FeliMe/AudioStyleNet#28]
i running the '$ python run_audiostylenet.py' cmd and got demo01.avi, but the file only 1 second 
what can i do for this?

**Comment by zydp** [comment]
could you help me?
thanks

**Comment by FeliMe** [comment]
Hi, this project was my Masters Thesis. Unfortunately, I do not have the time to actively maintain it anymore.

**Comment by zydp** [comment]
ok , thanks for your reply.

**Comment by zydp** [comment]
ok , thanks for your reply.
