### ISSUE TITLE
what is a RAIDROOT? You seem to put other projects under this path.

### ISSUE THREAD

**Issue by AY1997** [FeliMe/AudioStyleNet#3]
I cannot run the code because of this problem. Hope you can explain in detail, thank you.

**Comment by FeliMe** [comment]
$RAIDROOT was a location on an HDD on my server where I stored data (in RAIDROOT/Datasets/) and pre-trained models (in RAIDROOT/Networks/). I also had $DATAROOT which was the location on an SSD where I stored the data I was currently training with.

**Comment by AY1997** [comment]
Thank you, it's an impressive work. Since I don’t have these pre-trained models and data, do I have to train myself to get an available demo?

**Comment by FeliMe** [comment]
Thank you! I made some changes so you don't need to have the NVP and PCA model weights to just run the model. I also included a google colab demo notebook under the Demo section in the readme. You can try it out.
